spring.application.name=paymentgatewaysystem
server.port=8083

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://localhost:3306/paymentgateway
spring.datasource.username=root
spring.datasource.password=S@njai003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.api-docs.enabled=true
jwt.secret=mysecretkeymysupersecurekey8610998504
jwt.expiration.ms=86400000